title: Something witty
author: Greg
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Heres an awesome description for this site. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: chasinggreg # DO NOT include the @ character, or else the build will fail!
github_username:  chasinggreg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
